- name: Log into private registry
  docker_login:
    registry: 35.167.10.15:5000
    username: user
    password: "123"
    state: present

- name: Getting image from local registry for front
  shell: "docker pull  35.167.10.15:5000/backimage"

- name: Run container for front image
  docker_container:
    name: movie-analyst-api
    image: backimage
    state: started
    volumes:
    - "/etc/docker/movie-analyst-api:/var/lib/movie-analyst-api"
  published-ports:
    - "3000:3000"
