- name: Getting image from local registry for front
  docker_image:
    name: localhost:5000/frontimage
    repository: localhost:5000
    source: pull

- name: Run container for front image
  docker_container:
    name: movie-analyst-ui
    image: 54.189.87.199:5000/frontimage
    state: started
    volumes:
      - "/etc/docker/movie-analyst-ui:/var/lib/movie-analyst-ui"
    ports:
      - "3030:3030"
